"""股权激励归属与结算平台。"""
from __future__ import annotations

from .approvals import BatchStatus, Decision, FieldDiff, Role, SettlementBatch
from .errors import (
    AmendmentError,
    ConflictError,
    MissingMarketDataError,
    PlatformError,
    SettlementInputError,
    WorkflowError,
)
from .models import (
    DEFAULT_TERMINATION_POLICIES,
    AgreementTerms,
    BlackoutWindow,
    DateRange,
    FxRate,
    Grant,
    LeavePeriod,
    MarketPrice,
    PerformanceCondition,
    Receipt,
    ServicePeriod,
    SettlementMethod,
    SettlementRecord,
    TaxIdentity,
    Termination,
    TerminationPolicy,
    TerminationType,
    Tranche,
    TrancheSpec,
    TrancheStatus,
)
from .platform import EquityPlatform
from .settlement import SettlementQuote, compute_settlement
from .vesting import compute_vest_date, service_days_between

__all__ = [
    "AgreementTerms",
    "AmendmentError",
    "BatchStatus",
    "BlackoutWindow",
    "ConflictError",
    "DateRange",
    "Decision",
    "DEFAULT_TERMINATION_POLICIES",
    "EquityPlatform",
    "FieldDiff",
    "FxRate",
    "Grant",
    "LeavePeriod",
    "MarketPrice",
    "MissingMarketDataError",
    "PerformanceCondition",
    "PlatformError",
    "Receipt",
    "Role",
    "ServicePeriod",
    "SettlementBatch",
    "SettlementInputError",
    "SettlementMethod",
    "SettlementQuote",
    "SettlementRecord",
    "TaxIdentity",
    "Termination",
    "TerminationPolicy",
    "TerminationType",
    "Tranche",
    "TrancheSpec",
    "TrancheStatus",
    "WorkflowError",
    "compute_settlement",
    "compute_vest_date",
    "service_days_between",
]
